name: build_pr
on:
  push:
    branches:
    - main
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Start DB containers
      run: docker-compose -f "tests/docker-compose.yml" up -d
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.19.0'
    - name: Install dependencies
      run: |
        go version
        go mod tidy
    - name: Run build
      run: |
        go build . 
    - name: Run testing
      run: |
        go test -v ./...
    - name: Run vetting
      run: |
        go vet -v ./...
    - name: Stop DB containers
      if: always()
      run: docker-compose -f "test/docker-compose.yml" down
